### ISSUE TITLE
Setup & Install with ESPHome?

### ISSUE THREAD

**Issue by pixelwave** [yoziru/esphome-tesla-ble#37]
I tried to copy and install this script via my **ESPHome (2024.7.2 / Docker)** but got the following error:

<img width="1778" alt="Screenshot 2024-07-26 at 12 38 55" src="https://github.com/user-attachments/assets/9049389d-24f9-482f-81d9-b2edb0af1822">

```
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

substitutions:
  friendly_name: ESPHome Tesla BLE
  device_name: tesla-ble
  device_description:  Tesla BLE

esphome:
  name: ${device_name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  comment: ${device_description}
  project:
    name: yoziru.esphome-tesla-ble
    version: "2024.7.24"
  libraries:
    - https://github.com/yoziru/tesla-ble.git#v2.1.0

packages:
  common: !include tesla-ble/common.yml
  client: !include tesla-ble/client.yml
  listener: !include tesla-ble/listener.yml # Uncomment this to scan find your VIN BLE MAC address

logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "..."

# sync time with home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

ota:
  - platform: esphome
    password: "..."


esp32_ble_tracker:
  scan_parameters:
    # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
    continuous: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-08-Tesla-Ble"
    password: "EuiIlgkmbgWj"
  # Activate scan only after wifi connect, see https://github.com/esphome/issues/issues/2941#issuecomment-1842369092
  on_connect:
    - esp32_ble_tracker.start_scan:
       continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:

captive_portal:    
```
