### ISSUE TITLE
cant figure out how to compile the listener thing

### ISSUE THREAD

**Issue by itiotdk** [yoziru/esphome-tesla-ble#60]
hi. the insctructions are unclear
i need someone to explain excatly what to do. as there is nothing in base to change...

i can compile the final code. but i just dont get the listenser part and cant get my mac...

thanks. andy

**Comment by janchrillesen** [comment]
In the file packages/base.yml you need to add the following line under packages:

`  listener: !include listener.yml`

After the addition the packages section will look like:

```
packages:
  board: !include board.yml
  common: !include common.yml
  project: !include project.yml
  listener: !include listener.yml
```
