### ISSUE TITLE
ATOM Lite Reference File

### ISSUE THREAD

**Issue by sumur1au** [yoziru/esphome-tesla-ble#66]
For reference if anyone wants to use the ATOM Lite for the Tesla BLE Project

```
substitutions:
  name: ble-tesla
  friendly_name: Ble Tesla
  charging_amps_max: "16"

packages:
  common: github://yoziru/esphome-tesla-ble/packages/common.yml@main
  client: github://yoziru/esphome-tesla-ble/packages/client.yml@main
# listener: github://yoziru/esphome-tesla-ble/packages/listener.yml@main

external_components:
  source: github://yoziru/esphome-tesla-ble/packages/external_components.yml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  libraries:
    - https://github.com/yoziru/tesla-ble.git  

esp32:
  board: m5stack-atom
  flash_size: 4MB
  framework:
    type: esp-idf
    version: 5.3.0
    platform_version: 6.8.1 

####################################################
wifi:
  fast_connect: true
  ssid: !secret IoT_ssid
  password: !secret IoT_password
  on_connect:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_disconnect:
    - esp32_ble_tracker.stop_scan:
  output_power: 8.5dBm  

  # Enable fallback hotspot (for captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome $friendly_name"
    password: !secret ap_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret api_ota_Password

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password  
  
####################################################

# Enable logging
logger:
```
